name: Docs tracker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  track-docs:
    runs-on: ubuntu-latest
    name: Checking Docs
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Svelte/SvelteKit tutorial new commits
        uses: AlexxNB/track-commits-to-issue@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: sveltejs
          repo: learn.svelte.dev
          dir: content/tutorial
